Feature/issue 6 submission function
ga4gh/ga4gh-testbed-lib pull request #7
Opened 2022-04-04 17:30 UTC by Chen2x

Created a submission function for making post requests to the testbed api

2022-04-04 18:39 UTC, jb-adams requested changes
Looks good so far. I have the following suggestions:
* To make this even simpler, you could remove the `__init__` constructor and make `submit_report` a static method that accepts a url, series id, series token, and report
* make `url` a keyword argument, with a default value of the test endpoint, e.g.
```
def submit_report(..., url="http://localhost:4500/reports")
```

There's also no test code for this module. When you add your unit tests, assume that there is a running testbed api at `http://localhost:4500`, and that it has the two test report series we discussed

2022-04-04 18:39 UTC, jb-adams commented on ga4gh/testbed/submit/submit_to_api.py
> +class Submit():
could be more descriptive, maybe `ReportSubmitter`?

2022-04-04 18:39 UTC, jb-adams commented on ga4gh/testbed/submit/submit_to_api.py
> +    def submit_report(self):
please add docstring for the method

2022-04-06 12:53 UTC, jb-adams requested changes
In the last review, I mentioned:

> There's also no test code for this module. When you add your unit tests, assume that there is a running testbed api at http://localhost:4500, and that it has the two test report series we discussed

I'm still not seeing any test code, which means there's no way to know if the function works correctly or breaks in the future. Can you please add tests?

2022-04-06 13:12 UTC, Chen2x commented
Whoops I missed that part. Adding the tests in today.

2022-04-07 18:55 UTC, jb-adams requested changes
in addition to the inline comments, the failing tests should also be addressed

2022-04-07 18:55 UTC, jb-adams commented on ga4gh/testbed/submit/report_submitter.py
> +        return submit_request.status_code
Returning the status code from this method is insufficient, especially if there's been an error we want to know why (i.e. the message). If the submission has been successful, then we want the `id` of the new report that was created on the server. So,

- Always return status code
- Return error message if submission wasn't successful, `None` if submission was successful
- Return new report id if submission was successful, `None` if submission wasn't successful

Should be pretty easy to do in a Python dictionary

2022-04-08 13:42 UTC, jb-adams approved these changes

2022-04-08 13:43 UTC, merged